import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import StripeModal from '../components/StripeModal2'
import StripeForm2 from '../components/StripeForm2'

export default function Home() {
	const [modalIsOpen, setModalIsOpen] = useState(false)
  const openModal = () => {
    setModalIsOpen(true);
  }

  const afterOpenModal = () => {
    // references are now sync'd and can be accessed.
    subtitle.style.color = '#f00';
  }

  const closeModal = () => {
    setModalIsOpen(false)
	}

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
				<script src="https://js.stripe.com/v3/" />
      </Head>

      <main className={styles.main}>
				<StripeForm2 />
				<button id="modal-open-button" onClick={openModal}>Open Modal</button>
      </main>

			<StripeModal 
				modalIsOpen={modalIsOpen}
				closeModal={closeModal} />
    </div>
  )
}
